import type { Tables } from "@/lib/database.types";

export const mockTransactions: Tables<'transactions'>[] = [
  {
    id: "1",
    household_id: "",
    date: "2025-11-04",
    category: "Tere",
    tipo: "gasto",
    monto: 400,
    persona: "Compartido",
    metodo: null,
    nota: "Pago mes",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    household_id: "",
    date: "2025-11-04",
    category: "Deporte",
    tipo: "gasto",
    monto: 99,
    persona: "Compartido",
    metodo: null,
    nota: "Monkeyfit",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    household_id: "",
    date: "2025-11-04",
    category: "Extras",
    tipo: "gasto",
    monto: 5,
    persona: "Compartido",
    metodo: null,
    nota: "Tambo agua",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    household_id: "",
    date: "2025-11-04",
    category: "Restaurantes",
    tipo: "gasto",
    monto: 94,
    persona: "Compartido",
    metodo: null,
    nota: "Postre almuerzo Anita",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    household_id: "",
    date: "2025-11-04",
    category: "Extras",
    tipo: "gasto",
    monto: 200,
    persona: "Compartido",
    metodo: null,
    nota: "Marco Antonio Solis",
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    household_id: "",
    date: "2025-11-04",
    category: "Estacionalidad",
    tipo: "gasto",
    monto: 736,
    persona: "Compartido",
    metodo: null,
    nota: "Alquiler casa feriado",
    created_at: new Date().toISOString(),
  },
  {
    id: "7",
    household_id: "",
    date: "2025-11-04",
    category: "Compras Casa",
    tipo: "gasto",
    monto: 285,
    persona: "Compartido",
    metodo: null,
    nota: "Compras Tottus",
    created_at: new Date().toISOString(),
  },
  {
    id: "8",
    household_id: "",
    date: "2025-11-04",
    category: "Carro",
    tipo: "gasto",
    monto: 25,
    persona: "Compartido",
    metodo: null,
    nota: "Lavada en Tottus",
    created_at: new Date().toISOString(),
  },
  {
    id: "9",
    household_id: "",
    date: "2025-11-04",
    category: "Extras",
    tipo: "gasto",
    monto: 21,
    persona: "Compartido",
    metodo: null,
    nota: "Agave",
    created_at: new Date().toISOString(),
  },
];
